---
 - name: "Create a subnet group for caches for {{ company }}-{{ server_role }}-{{ env }}"
   elasticache_subnet_group:
     state: present
     name: "{{ company }}-{{ server_role }}-{{ env }}-redis-subnet-group"
     description: "subnet group for redis for {{ company }}-{{ server_role }}-{{ env }} in {{ region }}"
     subnets: "{{ subnets }}"
     region: "{{ region }}"

 - name: "Create the Redis instance for {{ company }}-{{ server_role }}-{{ env }}"
   elasticache:
     name: "{{ server_role }}-redis"
     state: present
     engine: redis
     node_type: cache.t2.micro
     num_nodes: 1
     region: eu-west-1
     zone: eu-west-1a
     security_group_ids: "{{ group_id }}"
     cache_subnet_group: "{{ company }}-{{ server_role }}-{{ env }}-redis-subnet-group"
     hard_modify: true
     wait: yes
   register: cache

 - name: "Register CNAME for elasticache in {{ private_domain }}"
   route53:
     command: create
     zone: "{{ private_domain }}"
#     hosted_zone_id: "{{ zone_out_private.set.zone_id }}"
     record: "cache.{{ private_domain }}"
     type: CNAME
     ttl: 7200
     value: "{{ cache.elasticache.data.CacheNodes[0].Endpoint.Address  }}"
     overwrite: yes
     private_zone: true




