---
 - name: Create a subnet group for caches
   elasticache_subnet_group:
     state: present
     name: "navi-web-redis-subnet-group"
     description: "Redis eu-west-1 subnet group"
     subnets: "{{ subnets }}"
     region: "eu-west-1"

 - name: Create the Redis instance for
   elasticache:
     name: "navi-web-redis"
     state: present
     engine: redis
     node_type: cache.t2.micro
     num_nodes: 1
     region: eu-west-1
     zone: eu-west-1a
     cache_subnet_group: "navi-web-redis-subnet-group"
     hard_modify: true
     wait: yes
   register: cache

 - name: Register CNAME for elasticache
   route53:
     command: create
     zone: "{{ private_domain }}"
     record: "cache.{{ private_domain }}"
     type: CNAME
     ttl: 7200
     value: "{{ cache.elasticache.data.CacheNodes[0].Endpoint.Address  }}"
     overwrite: yes
