 - name: Launch load balancer
   ec2_elb_lb:
     name: "navi-web-lb"
     region: "{{ region }}"
     state: present
     subnets: "{{ subnets }}"
     connection_draining_timeout: 60
     listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 80
       - protocol: https
         load_balancer_port: 443
         instance_protocol: http
         instance_port: 80
         ssl_certificate_id: "{{ ssl_certificate_id }}"
     health_check:
         ping_protocol: http
         ping_port: 80
         ping_path: "/about"
         response_timeout: 5
         interval: 30
         unhealthy_threshold: 2
         healthy_threshold: 10
   register: load_balancer
   
   debug: var=load_balancer   

 - name: Add load_balancer name in var file
   lineinfile:
     dest: vars/settings.yml
     line: |
         lb_name: "{{ load_balancer.elb.name }}"
     create: true

 - name: Register CNAME record for web-app balancer
   route53:
     command: create
     zone: "{{ public_domain }}"
     record: "{{ subdomain}}.{{ public_domain }}"
     type: CNAME
     ttl: 7200
     value: "{{ load_balancer.elb.dns_name }}"
     overwrite: yes

 - name: Regiser A recod fo web-app balancer
   route53:
     command: create
     zone: "{{ public_domain }}
     record: "{{ public_domain }}"
     alias: true
     alias_hosted_zone_id="{{ load_balancer.elb.zone_id }}"
     type: A
     value: "{{ load_balancer.elb.dns_name }}"
     overwrite: yes
     when: subdomain == 'www'
