---

- name: webpack | Ensure dependencies are installed
  command: "npm install"
  args:
    chdir: "{{ application_path }}/app/static/"
#  become_user: naviplace

- name: webpack | Build bundle
  command: "node_modules/.bin/webpack -p"
  args:
    chdir: "{{ application_path }}/app/static/"
#  become_user: naviplace
  notify: restart application
