---

- name: webpack | Ensure dependencies are installed
  command: "npm install"
  args:
    chdir: "{{ application_path }}"
#  become_user: naviplace

- name: webpack | Build bundle
  command: "make prod"
  args:
    chdir: "{{ application_path }}"
#  become_user: naviplace
  notify: restart application
