- name: "ensure bash and OpenSSl and libssl are the latest versions"
  apt: "name={{ item }} update_cache=yes state=latest"
  become: yes
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: "install base packages"
  apt: "name={{ item }} update_cache=yes force=yes state=installed"
  become: yes
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python3-dev
    - python3-pip
    - python3-pycurl
    - supervisor
    - python-virtualenv
    - libffi-dev
    - libssl-dev
    - python-dev
  tags: packages

