---
- name: Provision base AMI Image
  hosts: base_ami
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  roles:
    - common
    - nginx
