---
# Environment specific variables
COMPANY: naviworld
ENVIRONMENT: dev
SERVER_ROLE: web

# Ubuntu AMI base image from packer
#AMI_NAME: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
#AMI_OWNER: "099720109477"

AWS_NAME: "navi-web"
AWS_REGION: "eu-east-1"
AWS_AVAILABILITY_ZONES: '"us-east-1a" "us-east-1b"'
AWS_AMI_IMAGE: "id"
AWS_INSTANCE_TYPE: "t1.micro"
AWS_SG: "navi_web"
AWS_ELB: "{{ AWS_NAME }}-elb"
AWS_VPC_ZONE: "navi-web"
AWS_SUBNETS: "navi-web"
AWS_IAM_PROFILE: "navi_web"
AWS_SSH_KEY: "navi_web"

AWS_ELB_LISTENERS:
  - protocol: http
    load_balancer_port: 80
    instance_protocol: http
    instance_port: 80
  - protocol: https
    load_balancer_port: 443
    instance_protocol: http
    instance_port: 443
    ssl_certificate_id: "arn:aws:iam::xxxxxxxxxxxx:server-certificate/navi-crt"

AWS_ELB_HEALTH_CHECK:
        ping_protocol: http # options are http, https, ssl, tcp
        ping_port: 80
        ping_path: "/" # not required for tcp or ssl
        response_timeout: 5 # seconds
        interval: 30 # seconds
        unhealthy_threshold: 2
        healthy_threshold: 10