---
- name: Ensure bash and OpenSSl and libssl are the latest versions
  apt: "name={{ item }} update_cache={{ update_apt_cache }} state=latest"
  sudo: yes
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: "name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed"
  sudo: yes
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python3-dev
    - python3-pip
    - python3-pycurl
    - supervisor
    - python-virtualenv
  tags: packages

- name: Install newrelic
  pip: name=newrelic executable=pip3
  sudo: yes
  tags: packages