---
- name: Ensure load balancer exists
  ec2_asg:
    name: special
    load_balancers: [ 'lb1', 'lb2' ]
    availability_zones: [ '{{ vpc_region }}' ]
    launch_config_name: 'lc-1'
    min_size: 1
    max_size: 3
    desired_capacity: 5
    vpc_zone_identifier: [ 'subnet-abcd1234', 'subnet-1a2b3c4d' ]
    tags:
      - environment: production
        propagate_at_launch: no