---
- name: Create Launch Configuration
  ec2_lc:
    name: '{{ AWS_NAME }}-lc'
    region: '{{ AWS_REGION }}'
    image_id: '{{ AWS_AMI_IMAGE }}'
    security_groups: '{{ AWS_SG }}'
    instance_type: '{{ AWS_INSTANCE_TYPE }}'
    instance_profile_name: '{{ AWS_IAM_PROFILE }}'
    assign_public_ip: yes
    key_name: '{{ AWS_SSH_KEY }}'

- name: Create Auto Scaling Group
  ec2_asg:
    name: '{{ AWS_NAME }}-asg'
    load_balancers: ['{{ AWS_ELB }}']
    launch_config_name: '{{ AWS_NAME }}-lc'
    health_check_period: 300
    health_check_type: ELB
    replace_all_instances: yes
    min_size: 1
    max_size: 3
   #desired_capacity: 2
    region: '{{ AWS_REGION }}'
    availability_zones: '{{ AWS_AVAILABILITY_ZONES }}'
    vpc_zone_identifier: '{{ AWS_SUBNETS }}'
    wait_for_instances: True
    wait_timeout: 300
    tags:
      - environment: production
        propagate_at_launch: no
