---
- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart gunicorn
  service: name=gunicorn_start state=restarted

- name: restart nginx
  service: name=nginx state=restarted