 - name: Launch load balancer
   ec2_elb_lb:
     name: "navi-web-lb"
     region: "{{ region }}"
     state: present
     subnets: "{{ subnets }}"
     connection_draining_timeout: 60
     listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 80
     health_check:
         ping_protocol: http
         ping_port: 80
         ping_path: "/"
         response_timeout: 5
         interval: 30
         unhealthy_threshold: 3
         healthy_threshold: 3
   register: load_balancer

 - name: Add load_balancer name in var file
   lineinfile:
     dest: vars/settings.yml
     line: |
         lb_name: "{{ load_balancer.elb.name }}"
     create: true

 - name: Register CNAME record for web-app balancer
   route53:
     command: create
     zone: naviaddress.local
     record: www.naviaddress.local
     type: CNAME
     ttl: 7200
     value: "{{ load_balancer.elb.dns_name }}"
     overwrite: yes

