 - name: Create ec2 key pair
   ec2_key:
     name: navi-web
     state: present
   register: key

 - name: Add key pair name in var file
   lineinfile:
     dest: vars/settings.yml
     line: |
         key_name: "{{ key.key.name }}"
         private_key_path: "~/.ssh/id_rsa_navi"
     create: true

 - name: Add private key in ~/.ssh/id_rsa_navi
   blockinfile:
     marker: ' '
     dest: ~/.ssh/id_rsa_navi
     block: |
       {{ key.key.private_key }}
     create: true
     mode: 0600
   when: download_key is defined and download_key|bool == True
