ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

group_id: sg-2d515249
ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

lb_name: "navi-web-lb"

