ami_id: "ami-f95ef58a"

key_name: "navi-web"
private_key_path: "~/.ssh/id_rsa_navi"

vpc_id: "vpc-6b36380e"
subnets: 
  - "subnet-3896665c"
  - "subnet-0ee7fe79"

group_id: sg-2d515249
lb_name: "navi-web-lb"

app_image_id: ami-7cf8430f
lc_suffix: 1457642761

