 - hosts: aws
   vars_files:
    - vars/settings.yml
   tasks:
    - name: Get vpc facts
      ec2_vpc_net_facts:
        filters:
          "tag:Name": naviworld-dev-vpc
      register: vpc

    - name: Get vpc subnet facts
      ec2_vpc_subnet_facts:
        filters:
          vpc-id: "{{ vpc.vpcs[0].id }}"
      register: subnets

    - name: Create prerender instance
      ec2:
        assign_public_ip: yes
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        group_id: "{{ group_id }}"
        instance_type: t2.micro
        vpc_subnet_id: "{{ subnets.subnets[0].id }}"
        image: "ami-f95ef58a"
        wait: yes
        wait_timeout: 300
        exact_count: 1
        count_tag:
          role: prerender
        instance_tags:
          role: prerender
      register: prerender
 
    - name: Wait for SSH to start
      wait_for: host={{ prerender.tagged_instances.0.public_ip }} port=22 delay=60 timeout=180 state=started

    - name: add host to group
      add_host: name={{ prerender.tagged_instances.0.public_ip }} groups=just_created
    
    - name: Register CNAME for prerender instance
      route53:
        command: create
        zone: naviaddress.local
        record: prerender.naviaddress.local
        type: CNAME
        ttl: 7200
        value: "{{ prerender.tagged_instances.0.public_dns_name }}"
        overwrite: yes

 - hosts: just_created
   remote_user: ubuntu
   roles:
     - common
