---
- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }} recurse=yes owner={{ gunicorn_user }} group={{ gunicorn_group }} state=directory
  notify: restart application

- name: restart nginx
  service: name=nginx state=restarted

- name: restart supverisor
  service: name=supervisor state=restarted