---
 - name: Get vpc facts
   ec2_vpc_net_facts:
     filters:
       "tag:Name": naviworld-dev-vpc
   register: vpc

 - name: Get vpc subnet facts
   ec2_vpc_subnet_facts:
     filters:
       vpc-id: "{{ vpc.vpcs[0].id }}"
   register: subnets

 - name: Create a subnet group for caches
   elasticache_subnet_group:
     state: present
     name: "navi-web-redis-subnet-group"
     description: "Redis eu-west-1 subnet group"
     subnets:
      - "{{ subnets.subnets[0].id }}"
      - "{{ subnets.subnets[1].id }}"
     region: eu-west-1

 - name: Create the Redis instance for
   elasticache:
     name: "navi-web-redis"
     state: present
     engine: redis
     node_type: cache.m3.medium
     num_nodes: 1
     region: eu-west-1
     zone: eu-west-1a
     hard_modify: true
#     cache_subnet_group: "navi-web-redis-subnet-group"
     wait: yes
   register: cache

 - name: Register CNAME for elasticache
   route53:
     command: create
     zone: naviaddress.local
     record: cache.naviaddress.local
     type: CNAME
     ttl: 7200
     value: "{{ cache.elasticache.data.CacheNodes[0].Endpoint.Address  }}"
     overwrite: yes
#     wait: yes
