---
 - name: Create a subnet group for caches
   elasticache_subnet_group:
     state: present
     name: "navi-web-redis-subnet-group"
     description: "Redis eu-west-1 subnet group"
     subnets:
      - subnet-fa30da9e
     region: eu-west-1

 - name: "Create the Redis instance for"
   elasticache:
     name: "navi-web-redis"
     state: present
     engine: redis
     node_type: cache.m3.medium
     num_nodes: 2
     region: eu-west-1
     zone: eu-west-1a
     cache_subnet_group: "navi-web-redis-subnet-group"
     wait: yes
