- elasticache:
    name: "navi-web-redis"
    state: present
    engine: redis
    cache_engine_version: 2.8.24
    node_type: cache.m3.medium
    num_nodes: 1
    cache_port: 6379
    cache_security_groups:
      - default
    zone: eu-west-1

#- elasticache_subnet_group:
#    state: present
#    name: norwegian-blue
#    description: My Fancy Ex Parrot Subnet Group
#    subnets:
#      - subnet-aaaaaaaa
#      - subnet-bbbbbbbb