- name: Create Elasticache subnet group
  elasticache_subnet_group:
    state: present
    description: "nwrsg"
    name: "navi-web-redis-subnet-group"
    subnets:
      - subnet-2aa02851
      - subnet-43295c2a
  register: ecsg

- elasticache:
    name: "navi-web-redis"
    state: present
    engine: redis
    cache_engine_version: 2.8.24
    node_type: cache.m3.medium
    num_nodes: 1
    cache_port: 6379
    cache_subnet_groups:
      - "{{ ecsg }}"
    zone: eu-west-1

