---
- name: terminate old instances
  hosts: all
  tasks:
    - action: ec2_facts
    - name: terminating old instances
      local_action:
        module: ec2
        state: 'absent'
        region: 'us-east-1'
        keypair: 'myapp'
        instance_ids: "{{ ansible_ec2_instance_id }}"