---
 - name: Create VPC
   ec2_vpc:
     state: present
     cidr_block: 172.22.0.0/16
     resource_tags: { "Environment":"{{ app_name }}-vpc" }
     subnets:
       - cidr: 172.22.1.0/24
         az: eu-west-1a
         resource_tags: { "Name":"{{ app_name }}-1" }
       - cidr: 172.22.2.0/24
         az: eu-west-1b
         resource_tags: { "Name":"{{ app_name }}-2" }
     internet_gateway: True
     route_tables:
       - subnets:
           - 172.22.1.0/24
           - 172.22.2.0/24
         routes:
           - dest: 0.0.0.0/0
             gw: igw
     region: eu-west-1
   register: vpc

 - name: Add VPC id and subnets in var file
   lineinfile:
     dest: vars/settings.yml
     line: |
       vpc_id: "{{ vpc.vpc_id }}"
       subnets: 
         - "{{ vpc.subnets.0.id }}"
         - "{{ vpc.subnets.1.id }}"
     create: true
