---
 - name: "Create {{ private_domain }} dns zone"
   route53_zone:
     vpc_id: "{{ vpc.vpc_id }}"
     vpc_region: "{{ region }}"
     zone: "{{ private_domain }}"
     state: present
   register: zone_out_private

 - name: "Create {{ public_domain }} dns zone"
   route53_zone:
     zone: "{{ public_domain }}"
     state: present
   register: zone_out_public

