---
 - name: Create naviaddress.local dns zone
   route53_zone:
     vpc_id: "{{ vpc.vpc_id }}"
#     vpc_region: "{{ ec2_region }}"
     zone: "{{ vpc_dns_zone }}"
     state: present
   register: zone_out
