---
 - name: Get vpc facts
   ec2_vpc_net_facts:
     filters:
       "tag:Name": naviworld-dev-vpc
   register: vpc

 - name: Create security group for web app
   ec2_group:
     state: present
     name: navi-web
     description: security group for web app
     vpc_id: "{{ vpc.vpcs[0].id }}"
     rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0
   register: sg

 - name: Add security group id in var file
   lineinfile:
     dest: vars/settings.yml
     line: "group_id: {{ sg.group_id }}"
     state: present
