---
- name: Provision a {{ application_name }} server
  hosts: all  
  sudo: yes
  sudo_user: root
  remote_user: <remote user>
  private_key_file: </path/to/file.pem>
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml
  roles:
    - common
    - nginx
    - gunicorn
    - celery
    - redis
